export const rentHouses = [
  {
    id: 1,
    type: "featured",
    mainImage: "/Rent-houses/House-1/home1-1.jpg",
    moreImages: [
      "/Rent-houses/House-1/home1-2.jpg",
      "/Rent-houses/House-1/home1-3.jpg",
      "/Rent-houses/House-1/home1-4.jpg",
      "/Rent-houses/House-1/home1-5.jpg",
    ],
    name: "Delhi",
    address: "DHA 9 City, Delhi, India",
    price: 13000000,
    details: [
      "4 Bedrooms",
      "3 attached Bathrooms",
      "2 common Bathrooms",
      "2 Kitchens",
      "Beautifully designed structure",
      "Unfurnished",
      "Best Location",
      "Area: 10 marla",
    ],
    description:
      "DHA 9 Housing Scheme A block 10 Marla New brand house available for sale Good location house near by hospital, market, masjid, LGS school, and other facilities.",
  },
  {
    id: 2,
    type: "featured",
    mainImage: "/Rent-houses/House-2/home2-1.jpg",
    moreImages: [
      "/Rent-houses/House-2/home2-2.jpg",
      "/Rent-houses/House-2/home2-3.jpg",
      "/Rent-houses/House-2/home2-4.jpg",
      "/Rent-houses/House-2/home2-5.jpg",
    ],
    name: "Mumbai",
    address: "Bahria Town, Mumbai, India",
    price: 10000000,
    details: [
      "4 Bedrooms",
      "1 big lounge",
      "4 attached Bathrooms",
      "1 common Bathroom",
      "2 Kitchens",
      "Beautiful garden with parking",
      "Half-furnished",
      "Area: 20 marla",
    ],
    description:
      "Bahria Town 20 Marla New brand house available for sale. Good location house near hospital, market, masjid, school, park, and other facilities in a fully developed society.",
  },
  {
    id: 3,
    type: "popular",
    mainImage: "/Rent-houses/House-3/home3-1.jpg",
    moreImages: [
      "/Rent-houses/House-3/home3-2.jpg",
      "/Rent-houses/House-3/home3-3.jpg",
      "/Rent-houses/House-3/home3-4.jpg",
      "/Rent-houses/House-3/home3-5.jpg",
    ],
    name: "Mumbai",
    address: "Gulistan-e-Johar, Mumbai, India",
    price: 5000000,
    details: [
      "Gulistan-e-Johar Block 7",
      "MAHAM PLAZA",
      "2 Bedrooms",
      "2 Bathrooms",
      "American design kitchen",
      "Floor Level: 1st floor",
      "Unfurnished",
      "Area: 950 sq. feet",
    ],
    description:
      "Apartment in installment. VIP location near park and masjid. Gulistan-e-Johar Mumbai. 950 Square Feet sized residential or commercial property is best for investment purposes.",
  },
  {
    id: 4,
    type: "popular",
    mainImage: "/Rent-houses/House-4/home4-1.jpg",
    moreImages: [
      "/Rent-houses/House-4/home4-2.jpg",
      "/Rent-houses/House-4/home4-3.jpg",
      "/Rent-houses/House-4/home4-4.jpg",
      "/Rent-houses/House-4/home4-5.jpg",
    ],
    name: "Bangalore",
    address: "Blue Area, F-3, Bangalore, India",
    price: 13500000,
    details: [
      "Location: Isra Tower",
      "2 Bedrooms",
      "Drawing Room",
      "2 Bathrooms",
      "2 Modern kitchens",
      "Floor Level: 1st floor",
      "Unfurnished",
      "Area: 1,100 sq. feet",
    ],
    description:
      "The Flat is well designed to accommodate the family and their guests. Location is everything, and we have many options regarding that. Perfect 1,100 Square Feet listing for your property needs.",
  },
  {
    id: 5,
    type: "popular",
    mainImage: "/Rent-houses/House-5/home5-1.jpg",
    moreImages: [
      "/Rent-houses/House-5/home5-2.jpg",
      "/Rent-houses/House-5/home5-3.jpg",
      "/Rent-houses/House-5/home5-4.jpg",
      "/Rent-houses/House-5/home5-5.jpg",
    ],
    name: "Chennai",
    address: "Saadi Town, Chennai, India",
    price: 9500000,
    details: [
      "Bunglow at Saadi town scheme",
      "4 Bedrooms",
      "A big drawing Room",
      "5 Bathrooms",
      "2 Modern style kitchens",
      "Unfurnished",
      "Car Parking",
      "Area: 120 sq. yards",
    ],
    description:
      "Saadi Town Brand New Project Bungalow Double Story 120 Sq Yards. Bedrooms with attached baths, drawing lounge, open American kitchen, washing area, huge terrace. Ideal location with main road access.",
  },
  {
    id: 6,
    type: "featured",
    mainImage: "/Rent-houses/House-6/home6-1.jpg",
    moreImages: [
      "/Rent-houses/House-6/home6-2.jpg",
      "/Rent-houses/House-6/home6-3.jpg",
      "/Rent-houses/House-6/home6-4.jpg",
      "/Rent-houses/House-6/home6-5.jpg",
    ],
    name: "Hyderabad",
    address: "Bahria Villas, Bahria Town, Hyderabad, India",
    price: 12000000,
    details: [
      "Bahria Villas, Bahria Town, Hyderabad",
      "5 Bedrooms",
      "Big drawing Room Lounge",
      "6 Bathrooms",
      "3 Modern style kitchens",
      "Unfurnished",
      "Indoor Car Parking",
      "Area: 120 sq. yards",
    ],
    description:
      "Well-designed house in a posh location with all modern amenities. Bahria Town's unique features, including 24/7 security, electricity, Jamia Masjid, petrol pump, and more.",
  },
];
